# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Install dependencies
RUN pip install --no-cache-dir mcp>=1.9.0 psutil>=5.9.0

# Set workdir
WORKDIR /app

# Copy project into container
COPY . /app

# Ensure Python unbuffered
ENV PYTHONUNBUFFERED=1

# Default command to run MCP server
ENTRYPOINT ["python", "-u", "server.py"]
